language: node_js
node_js:
- '0.10'
services:
- couchdb
before_install:
  - apt-get install selenium-webdriver
  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
install:
- python createviews.py
- npm install -g se-interpreter
- npm -g install forever
- forever start app.js
deploy:
  provider: cloudcontrol
  email: trautrims@gmail.com
  password:
    secure: "aQKsrJqeSJId5+WDDAhio5b0r9np/pnRQ6HTIto0mZjOXdEKKOtuxMhgNF+cmUf48Q+xgGX8t7O1W44/UTArw9lG2U1QYjMDozgaje0rPFPawNZpPJj9S4TaoS5K9JKJ9Sxl4NSVOj0lCFByTK85fS181SITvp+LvH9Wg3Q4hGg="
  deployment: cards/default
  on:
    repo: prinzmajus/thmcards
env:
  global:
  - secure: "BxceQZMQnKlq3vyYGTmwHK8THaQinsumatiXhwIcA7fWS1NsNdw2ci5KPDqbDUh2trnVF1IADlOCZCAUiQ5HBUZOEZxkPWdCNzZDMsWB8XTlSIYFMfpWZZE8m89slIFmOUfm6+8KVlOfZcpHBx3ri8TPwr281IkgoMhbYJcjpwI="
  - secure: "JgtmzxUu55wJM1TL5hnldFv3E6xtmW4qMAqcujHkNM5YB/bX+KQfBqUGSSXGCsFd/0ELzkOt5gpbxSCLoj9zC/+DMw7IQsBJXrtrkg7yqodrGymTnC/hyV8QuBDkaG2524kxh2hvKAWvfGCJwgSeoHQ6k9IToBpELswbvaLKMII="
addons:
  sauce_connect: true
script:
  #- se-interpreter selenium/interpreter_config.json
  - ruby selenium-tests/tmp.rb
