language: node_js
node_js:
- "0.10"
env:
  global:
    # Sauce Labs: (prinzmajus/thmcards) 1. User, 2. Access-Key
    - secure: "BxceQZMQnKlq3vyYGTmwHK8THaQinsumatiXhwIcA7fWS1NsNdw2ci5KPDqbDUh2trnVF1IADlOCZCAUiQ5HBUZOEZxkPWdCNzZDMsWB8XTlSIYFMfpWZZE8m89slIFmOUfm6+8KVlOfZcpHBx3ri8TPwr281IkgoMhbYJcjpwI="
    - secure: "JgtmzxUu55wJM1TL5hnldFv3E6xtmW4qMAqcujHkNM5YB/bX+KQfBqUGSSXGCsFd/0ELzkOt5gpbxSCLoj9zC/+DMw7IQsBJXrtrkg7yqodrGymTnC/hyV8QuBDkaG2524kxh2hvKAWvfGCJwgSeoHQ6k9IToBpELswbvaLKMII="
  matrix:
    - "BROWSER='firefox::Windows 7'"
    - "BROWSER='chrome::Windows 7'"
services:
  - couchdb
before_install:
  # Install tools required for GUI testing
  - "gem install selenium-webdriver"
  - "curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash"
  # Setup CouchDB
  - "python createviews.py"
before_script:
  # Download dependencies, install packages, run server
  - "npm -g install forever"
  - "forever start app.js"
script:
  # Run tests
  - "ruby saucelabs.rb"
deploy:
  provider: cloudcontrol
  email: trautrims@gmail.com
  password:
    secure: "aQKsrJqeSJId5+WDDAhio5b0r9np/pnRQ6HTIto0mZjOXdEKKOtuxMhgNF+cmUf48Q+xgGX8t7O1W44/UTArw9lG2U1QYjMDozgaje0rPFPawNZpPJj9S4TaoS5K9JKJ9Sxl4NSVOj0lCFByTK85fS181SITvp+LvH9Wg3Q4hGg="
  deployment: cards/default
  on:
    repo: prinzmajus/thmcards
addons:
  sauce_connect: true
