language: node_js
node_js:
- "0.10"
#- "0.8"
#- "0.6"
env:
  global:
    # Sauce Labs: (prinzmajus/thmcards) 1. User, 2. Access-Key
    - secure: "WXSTGMER67I1xl6/1ADnyopO5bu2DPd27eYie7sfA+PvWfEhKUGHGGswLGxX/vjXQA0TX6d8A6xOjztz6oGx/AqsRhedWMYhUySJxo9T/tCPSVQcCAAvaUmIL8PZGH+uH5qIb355FFmHQbs/li89Yy2cJY/Omc+IlCBEgb6Ko8A="
    - secure: "R09cHwGbgpuwqpm83+h0pUZpp+b6v/g9QK39n+wOAENhzFCE7Wmd50lFAGmD1e1YzHlGiJntO/eSBBDiCjZJyOeZDY1Yt8VA8mP7sjqw/2skDDX/tWBlNcZxHHoO2Mq47OZM3ePK/ehRcR4YKGEWCqEHxOj/NFMLdhFmLCjjEac="
  matrix:
    #- "BROWSER='firefox::Windows 7'"
    - "BROWSER='chrome::Windows 7'"
services:
  - couchdb
before_install:
  # Install tools required for GUI testing
  - "gem install selenium-webdriver"
  - "curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash"
  # Setup CouchDB
  - "python createviews.py"
before_script:
  # Download dependencies, install packages, run server
  - "npm -g install forever"
  - "forever start app.js"
script:
  # Run tests
  - "ruby saucelabs.rb"
deploy:
  provider: cloudcontrol
  email:
    secure: "MxJKt6tBspWQH/+LEzy11k+qBey65ziidvy4YxG4EUfiLhcFrSmNcpYsfyCyOn5MakFSCo4sHCoLr2XFVUgBPPzHWGS2hziwzFYOMw/VZZzlmmDTSJ0cewlWd+hwYX1U9hNi6HHvoLsBfruEJjfWRIDjAeANfSvXZzgmfrtGV2s="
  password:
    secure: "W4At/hxfUvjd+z/0iMZKgXpA81+mLkwFkHPzVEC3YxoFC5tYoPa9uWoA3HZxH+gimDXyizlYP/m9MJ5IqWQ5lFHntWPRb1FnemHOtQOy9CzNE9TcmaN3Wi9EST4jRt0/nofad6amZjDUdexVFycUEc9U+sZoJUhVxA1smiAND3k=" 
    deployment: cards/default
  on:
    repo: sewi22/thmcards
addons:
  sauce_connect: true
