language: node_js
node_js:
- '0.10'
services:
- couchdb
install:
- python createviews.py
deploy:
  provider: cloudcontrol
  email: trautrims@gmail.com
  password:
    secure: "aQKsrJqeSJId5+WDDAhio5b0r9np/pnRQ6HTIto0mZjOXdEKKOtuxMhgNF+cmUf48Q+xgGX8t7O1W44/UTArw9lG2U1QYjMDozgaje0rPFPawNZpPJj9S4TaoS5K9JKJ9Sxl4NSVOj0lCFByTK85fS181SITvp+LvH9Wg3Q4hGg="
  deployment: cards/default
  on:
    repo: prinzmajus/thmcards
env:
  global:
  - secure: "BxceQZMQnKlq3vyYGTmwHK8THaQinsumatiXhwIcA7fWS1NsNdw2ci5KPDqbDUh2trnVF1IADlOCZCAUiQ5HBUZOEZxkPWdCNzZDMsWB8XTlSIYFMfpWZZE8m89slIFmOUfm6+8KVlOfZcpHBx3ri8TPwr281IkgoMhbYJcjpwI="
  - secure: "JgtmzxUu55wJM1TL5hnldFv3E6xtmW4qMAqcujHkNM5YB/bX+KQfBqUGSSXGCsFd/0ELzkOt5gpbxSCLoj9zC/+DMw7IQsBJXrtrkg7yqodrGymTnC/hyV8QuBDkaG2524kxh2hvKAWvfGCJwgSeoHQ6k9IToBpELswbvaLKMII="
addons:
  sauce_connect: true
before_script:
- npm install -g se-interpreter
install:
  - sudo apt-get update -q
  - sudo apt-get install -q virtualbox --fix-missing # Everything falls apart here exactly.
  - sudo wget -nv https://dl.bintray.com/mitchellh/vagrant/vagrant_1.6.5_i686.deb
  - sudo dpkg -i vagrant_1.6.5_i686.deb
  - wget https://apt.puppetlabs.com/puppetlabs-release-precise.deb
  - sudo dpkg -i puppetlabs-release-precise.deb
  #- sudo vagrant plugin install vagrant-plugin-bundler
script:
  - sudo vagrant up # The error is only presented when executing vagrant up
  - se-interpreter selenium/interpreter_config.json
after-script:
  - sudo vagrant halt
  - sudo vagrant destroy
