language: node_js
node_js:
- "0.10"
#- "0.8"
#- "0.6"
env:
  global:
    # Sauce Labs: (prinzmajus/thmcards) 1. User, 2. Access-Key
    - secure: "WXSTGMER67I1xl6/1ADnyopO5bu2DPd27eYie7sfA+PvWfEhKUGHGGswLGxX/vjXQA0TX6d8A6xOjztz6oGx/AqsRhedWMYhUySJxo9T/tCPSVQcCAAvaUmIL8PZGH+uH5qIb355FFmHQbs/li89Yy2cJY/Omc+IlCBEgb6Ko8A="
    - secure: "R09cHwGbgpuwqpm83+h0pUZpp+b6v/g9QK39n+wOAENhzFCE7Wmd50lFAGmD1e1YzHlGiJntO/eSBBDiCjZJyOeZDY1Yt8VA8mP7sjqw/2skDDX/tWBlNcZxHHoO2Mq47OZM3ePK/ehRcR4YKGEWCqEHxOj/NFMLdhFmLCjjEac="
  matrix:
    #- "BROWSER='firefox::Windows 7'"
    - "BROWSER='chrome::Windows 7'"
services:
  - couchdb
before_install:
  # Install tools required for GUI testing
  - "gem install selenium-webdriver"
  - "curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash"
  # Setup CouchDB
  - "python createviews.py"
before_script:
  # Download dependencies, install packages, run server
  - "npm -g install forever"
  - "forever start app.js"
script:
  # Run tests
  #- "ruby saucelabs.rb"
deploy:
  provider: cloudcontrol
  email:
    secure: "aRwCuVKj1N1zkXizOeoq9b4nntOYYgcuwf/TOMFejhLcoFJvWDO4J8ynkSe/Ue5bw/oXeULV7h0JG35Xs+d5yqdMrdf4cnxHgtf+V0c4/rQbOPSbv3eKeoRdi6JVrGzPOGyTagLfrfSMhrkAne87hD1uG1oGuL94Q9qamldW8h8="
  password:
    secure: "BeV2B6BVYx9mSzqQugBd1Br1frYtinFkUQgqbdrt1j+xNW7Cqb0zDhMuqG4E6hjzccFnDOJS+t0Uf/xHOYWI74EylQZV2q4EeY6cUA8m9sV3fCnN40X6yiONBGoLV9u0oI5Ma+dFAJvYoZsS2d+RVuOis6mdjGaHe1HZrEgBZEQ="
    deployment: swthmcards/default
  on:
    repo: sewi22/thmcards
addons:
  sauce_connect: true
