language: node_js
node_js:
- "0.10"
#- "0.8"
#- "0.6"
env:
  global:
    # Sauce Labs: (RafaelKa/arsnova-flashcards)  
    ## User
    - secure: VMN65kmbQplleR+rOPev82PATLT3csO3gcNyBhQp9XNFx/t9892sef42bZbisahW/LjZl4sLcAV+IJEQEDwhci8gLC1TJ9ps6caMcgOlPx5pic8GoS8SAFszfP6IHhN2fSrh9UzjvqV6DxQdbJnBK5UnboWFE2J01sYx5p2nd5c=
    ## Access-Key
    - secure: XJrcF7KTyWZ1Kd7peMRleTklvNbRkqS05EgV8HxmHVWeCLC2L3RVS18WrLPkbs88CS42OSWWXpB+oZJQul81z3RQHQQo7M0zqw43rYnyv0m20WS0Ys5+ldsRg9CK56oEnvDK2Gjc9eu5uCb72/5hG026JyO80f3ywCYSTVRqni4=
services:
  - couchdb
before_install:
  # Setup CouchDB
  - "python createviews.py"
before_script:
  # Download dependencies, install packages, run server
  - "npm -g install forever se-interpreter"
  - "npm install"
  - "node app.js"
#  - "forever start app.js"
script:
  # Run tests
  - "se-interpreter tests/selenium-builder/se-interpreter-config.json"
#deploy:
#  provider: cloudcontrol
#  email:
#    secure: "ToDo"
#  password:
#    secure: "ToDo"
#  deployment: flashcards4rafaelka/default
#  on:
#    repo: RafaelKa/arsnova-flashcards
#addons:
#  sauce_connect: true
