language: node_js
node_js:
- '0.10'
services:
- couchdb
install:
- python createviews.py
before_script:
- npm install
- npm install -g se-interpreter
script:
- se-interpreter selenium/interpreter_config.json
env:
  global:
  - SAUCE_USERNAME=prinzmajus
  - secure: "HsaIFSPWKWh3dxxtRSsQEJi+3Dld+r0Vf4ypDTOsWwxQ88aAIj8d3Fs1bN9UXDgoo9ni1Hg7PT6X3cj6PWbc8ndml3dXqRGWEwhROQdAj2GvkzBNkMi2rAVCNSAYLqiApQBqt+f5XIoxpKTUAmvDDMB0zryh/AqyNmy1TfcK9Wg="
deploy:
  provider: cloudcontrol
  email: trautrims@gmail.com
  password:
    secure: "aQKsrJqeSJId5+WDDAhio5b0r9np/pnRQ6HTIto0mZjOXdEKKOtuxMhgNF+cmUf48Q+xgGX8t7O1W44/UTArw9lG2U1QYjMDozgaje0rPFPawNZpPJj9S4TaoS5K9JKJ9Sxl4NSVOj0lCFByTK85fS181SITvp+LvH9Wg3Q4hGg="
    deployment: cards/default
  on:
    repo: prinzmajus/thmcards
